# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPMri_g7GE4k38bRfjf1U_rFpeL-_pxX
"""

# app.py

import streamlit as st
import pandas as pd
from questions import QUESTIONS, TYPES, APP_TITLE, APP_DESCRIPTION, DISCLAIMER_TEXT, RESULT_COMMENTS
from scoring import calculate_scores, judge_result, build_score_table

st.set_page_config(page_title=APP_TITLE, page_icon="🩺", layout="centered")

st.title(APP_TITLE)
st.caption(APP_DESCRIPTION)
st.info(DISCLAIMER_TEXT)

red_flag = st.checkbox(
    "強い胸痛・強い息苦しさ・突然の激しい頭痛・高熱など、緊急性のある症状がある",
    value=False,
)

answers = {}

st.subheader("質問に答えてください")

# タイプごとにまとまって表示
for score_type in TYPES:
    st.markdown(f"## {score_type}")
    type_questions = [q for q in QUESTIONS if q["type"] == score_type]

    for q in type_questions:
        labels = [choice["label"] for choice in q["choices"]]
        selected_label = st.radio(
            q["text"],
            labels,
            key=q["id"]
        )
        answers[q["id"]] = labels.index(selected_label)

if st.button("診断する", type="primary"):
    totals = calculate_scores(answers, QUESTIONS)
    result_label, top_types = judge_result(totals, red_flag=red_flag)
    score_df = build_score_table(totals)

    st.subheader("診断結果")

    if result_label == "複合傾向":
        st.success(f"判定：複合傾向（{'・'.join(top_types)}）")
        comment = RESULT_COMMENTS["複合傾向"]
    else:
        st.success(f"判定：{result_label}")
        comment = RESULT_COMMENTS.get(result_label, "")

    st.write(comment)

    st.subheader("タイプ別スコア")
    st.bar_chart(score_df.set_index("タイプ"))

    st.dataframe(score_df, use_container_width=True, hide_index=True)

    # 最大スコアを強調
    st.subheader("スコアまとめ")
    max_score = score_df["点数"].max()
    top_df = score_df[score_df["点数"] == max_score]
    st.write("最も高いスコア：")
    st.dataframe(top_df, use_container_width=True, hide_index=True)
