# -*- coding: utf-8 -*-
"""questions.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H7Jc3BpkmnmubgvP-Tm71QxPAahbquBW
"""

APP_TITLE = "気血水スコア判定（試作版）"
APP_DESCRIPTION = "寺澤捷年先生の気血水スコアを一部改変したものです。参照：寺澤捷年著「症例から学ぶ和漢診療学」(医学書院)"
DISCLAIMER_TEXT = "このアプリはセルフチェック用の試作版です。医療上の診断を行うものではありません。"

TYPES = ["気虚", "気滞", "血虚", "瘀血", "水滞"]

QUESTIONS = [
    # -----------------
    # 気虚（ききょ）
    # -----------------
    {
        "id": "kikyo_1",
        "type": "気虚",
        "text": "体がだるいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "kikyo_2",
        "type": "気虚",
        "text": "気力はありますか？",
        "choices": [
            {"label": "ある", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "全然ない", "score": 10},
        ],
    },
    {
        "id": "kikyo_3",
        "type": "気虚",
        "text": "疲れやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "kikyo_4",
        "type": "気虚",
        "text": "日中に眠くなりやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 3},
            {"label": "かなりある", "score": 6},
        ],
    },
    {
        "id": "kikyo_5",
        "type": "気虚",
        "text": "食欲はありますか？",
        "choices": [
            {"label": "ない", "score": 4},
            {"label": "少しない", "score": 2},
            {"label": "ある", "score": 0},
        ],
    },
    {
        "id": "kikyo_6",
        "type": "気虚",
        "text": "風邪をひきやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kikyo_7",
        "type": "気虚",
        "text": "物事に驚きやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 4},
        ],
    },
    {
        "id": "kikyo_8",
        "type": "気虚",
        "text": "声に力がないですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しない", "score": 3},
            {"label": "ない", "score": 6},
        ],
    },

    # -----------------
    # 気滞（きたい）
    # -----------------
    {
        "id": "kitai_1",
        "type": "気滞",
        "text": "落ち込みやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 9},
            {"label": "かなりある", "score": 18},
        ],
    },
    {
        "id": "kitai_2",
        "type": "気滞",
        "text": "頭が重いと感じますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kitai_3",
        "type": "気滞",
        "text": "のどのつかえ感がありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kitai_4",
        "type": "気滞",
        "text": "胸がつかえた感じがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kitai_5",
        "type": "気滞",
        "text": "おなかがふくれいている感じがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kitai_6",
        "type": "気滞",
        "text": "時間により症状が変わりますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kitai_7",
        "type": "気滞",
        "text": "朝起きにくく調子が出ないですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
    {
        "id": "kitai_8",
        "type": "気滞",
        "text": "おならが出やすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 3},
            {"label": "かなりある", "score": 6},
        ],
    },



    # -----------------
    # 血虚（けっきょ）
    # -----------------
    {
        "id": "kekkyo_1",
        "type": "血虚",
        "text": "集中力が低下していますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 3},
            {"label": "かなりある", "score": 6},
        ],
    },
    {
        "id": "kekkyo_2",
        "type": "血虚",
        "text": "夜眠れないですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 3},
            {"label": "かなりある", "score": 6},
        ],
    },
    {
        "id": "kekkyo_3",
        "type": "血虚",
        "text": "眼が疲れていますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 6},
            {"label": "かなりある", "score": 12},
        ],
    },
   {
        "id": "kekkyo_4",
        "type": "血虚",
        "text": "めまいがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
   {
        "id": "kekkyo_5",
        "type": "血虚",
        "text": "足がつりやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
   {
        "id": "kekkyo_6",
        "type": "血虚",
        "text": "顔色が悪いですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
   {
        "id": "kekkyo_7",
        "type": "血虚",
        "text": "髪の毛が抜けやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },
   {
        "id": "kekkyo_8",
        "type": "血虚",
        "text": "皮膚が乾燥していたり荒れてたりしますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 7},
            {"label": "かなりある", "score": 14},
        ],
    },
   {
        "id": "kekkyo_9",
        "type": "血虚",
        "text": "爪の形に異常がありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 4},
            {"label": "かなりある", "score": 8},
        ],
    },


    # -----------------
    # 瘀血（おけつ）
    # -----------------
    {
        "id": "oketsu_1",
        "type": "瘀血",
        "text": "眼のくまができていますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "oketsu_2",
        "type": "瘀血",
        "text": "肌が荒れていますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 5},
        ],
    },
    {
        "id": "oketsu_3",
        "type": "瘀血",
        "text": "歯茎の色が暗い色ですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "oketsu_4",
        "type": "瘀血",
        "text": "舌の色が暗い赤紫色ですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "oketsu_5",
        "type": "瘀血",
        "text": "へその斜め下を押すと痛いですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "oketsu_6",
        "type": "瘀血",
        "text": "痔ですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },
    {
        "id": "oketsu_7",
        "type": "瘀血",
        "text": "月経障害がありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 5},
            {"label": "かなりある", "score": 10},
        ],
    },



    # -----------------
    # 水滞（すいたい）
    # -----------------
    {
        "id": "suitai_1",
        "type": "水滞",
        "text": "体が重い感じがしますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 1},
            {"label": "かなりある", "score": 3},
        ],
    },
    {
        "id": "suitai_2",
        "type": "水滞",
        "text": "頭が重い感じがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 1},
            {"label": "かなりある", "score": 3},
        ],
    },
    {
        "id": "suitai_3",
        "type": "水滞",
        "text": "頭痛がありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 4},
        ],
    },
    {
        "id": "suitai_4",
        "type": "水滞",
        "text": "車酔いしやすいですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 5},
        ],
    },
    {
        "id": "suitai_5",
        "type": "水滞",
        "text": "めまいがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 5},
        ],
    },
    {
        "id": "suitai_6",
        "type": "水滞",
        "text": "立ちくらみがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 5},
        ],
    },
    {
        "id": "suitai_7",
        "type": "水滞",
        "text": "無色透明な鼻水が出ますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 1},
            {"label": "かなりある", "score": 3},
        ],
    },
    {
        "id": "suitai_8",
        "type": "水滞",
        "text": "痰に泡が多く含まれますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 4},
        ],
    },
    {
        "id": "suitai_9",
        "type": "水滞",
        "text": "吐き気がありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 1},
            {"label": "かなりある", "score": 3},
        ],
    },
        {
        "id": "suitai_10",
        "type": "水滞",
        "text": "朝、関節がこわばりますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 3},
            {"label": "かなりある", "score": 7},
        ],
    },
    {
        "id": "suitai_11",
        "type": "水滞",
        "text": "むくみがありますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 7},
            {"label": "かなりある", "score": 15},
        ],
    },
    {
        "id": "suitai_12",
        "type": "水滞",
        "text": "下痢をしていますか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "少しある", "score": 2},
            {"label": "かなりある", "score": 5},
        ],
    },
    {
        "id": "suitai_13",
        "type": "水滞",
        "text": "尿の量が少ないですか？",
        "choices": [
            {"label": "いいえ、普通", "score": 0},
            {"label": "少ない", "score": 3},
            {"label": "かなり少ない", "score": 7},
        ],
    },
    {
        "id": "suitai_14",
        "type": "水滞",
        "text": "尿の量や回数が多いですか？",
        "choices": [
            {"label": "いいえ", "score": 0},
            {"label": "一日7回以上", "score": 2},
            {"label": "一日10回以上", "score": 5},
        ],
    },

]

RESULT_COMMENTS = {
    "気虚": "気虚（ききょ）スコアが最も高く、疲れやすさやエネルギー不足の傾向が示唆されます。",
    "気滞": "気滞（きたい）スコアが最も高く、ストレスによる巡りの停滞傾向が示唆されます。",
    "血虚": "血虚（ききょ）スコアが最も高く、うるおい・栄養不足傾向が示唆されます。",
    "瘀血": "瘀血（おけつ）スコアが最も高く、巡りの滞り傾向が示唆されます。",
    "水滞": "水滞（すいたい）スコアが最も高く、水分代謝の停滞傾向が示唆されます。",
    "複合傾向": "複数タイプのスコアが同点で高く、複合傾向が考えられます。",
    "大きな偏りなし": "現時点では特定タイプへの大きな偏りは目立ちません。",
    "要受診確認": "緊急性のある症状があるため、医療機関への相談を優先してください。",
}
