# -*- coding: utf-8 -*-
"""scoring.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jlq3ZMhLyq8Xp5pumHa94xftGnDpLVp
"""

# scoring.py

import pandas as pd
from questions import TYPES

def calculate_scores(answers, questions):
    """
    answers: {"kikyo_1": 2, "kikyo_2": 1, ...}
    questions: QUESTIONS
    """
    totals = {t: 0 for t in TYPES}

    for q in questions:
        selected_index = answers.get(q["id"])
        if selected_index is None:
            continue

        selected_choice = q["choices"][selected_index]
        score = selected_choice["score"]
        q_type = q["type"]

        totals[q_type] += score

    return totals


def judge_result(totals, red_flag=False):
    if red_flag:
        return "要受診確認", []

    max_score = max(totals.values())

    if max_score == 0:
        return "大きな偏りなし", []

    top_types = [t for t, score in totals.items() if score == max_score]

    if len(top_types) == 1:
        return top_types[0], top_types

    return "複合傾向", top_types


def build_score_table(totals):
    return pd.DataFrame({
        "タイプ": list(totals.keys()),
        "点数": list(totals.values()),
    })